from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookViewSet

# Create a router instance
router = DefaultRouter()

# Register our BookViewSet with the router
# 'books' is the prefix for all URLs generated by this router (e.g., /books/)
router.register(r"books", BookViewSet)

# app_name helps Django namespace the URLs, preventing naming conflicts
app_name = "books"

# The API URLs are determined automatically by the router
urlpatterns = [
    path("", include(router.urls)),
]
