# Generated by Django 6.1 on 2026-09-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
